name: MinesExpanded
version: '${version}'
main: me.deathrealms.minesexpanded.MinesExpanded
api-version: '1.13'
authors: [DeathRealms]
depend:
  - WorldEdit
description: Create fully customizable mines on your server!
